name: Integration

on:
  push:
    branches: ["master"]
  # Allows running this workflow manually from the Actions tab.
  workflow_dispatch:
  # Runs the workflow on the first day of every month
  schedule:
    - cron: '0 0 1 * *'

jobs:
  check:
    strategy:
      matrix:
        include:
          - {name: etv, repo: term-validator}
          - {name: spawn_mode, repo: spawn-mode}
          - {name: otpless_worker, repo: otpless-worker}
          - {name: otpless_orchestrator, repo: otpless-orchestrator}
          - {name: otpless_reactor, repo: otpless-reactor}

    runs-on: ubuntu-latest
    container:
      image: erlang:latest

    steps:
      - name: Get the source code
        uses: actions/checkout@v3

      - name: Download latest rebar3
        run: |
          cd myproject
          wget https://s3.amazonaws.com/rebar3/rebar3
          chmod +x rebar3

      - name: Check project integration
        run: |
          cd myproject
          sed \
            -e 's/@project_name/${{matrix.name}}/g' \
            -e 's/@project_repo/${{matrix.repo}}/g' \
            rebar.config.in > rebar.config
          ./rebar3 compile
